<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_TSN_tsn</name>
   <tag></tag>
   <elementGuidId>83752136-3a05-429e-ba7d-dd8837d0968a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='tsn']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>TextInput__textInput--3aA1s EnterHsnTsnView__inputField--28BxH</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>___</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>tsn</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;AppView__appView--3Wb7Q&quot;]/div[3]/div[@class=&quot;AppView__mainContent--238OV AppView__withNavBar--1ob7E&quot;]/div[@class=&quot;WizardTransitionContainer__transitionGroupWrapper--1xFky&quot;]/div[1]/div[1]/div[@class=&quot;WizardForm__main--jXVbZ WizardTransitionContainer__slideForward--375Hb&quot;]/form[@class=&quot;WizardForm__form--JULwv WizardForm__hasScreenHeight--3Vg4P&quot;]/div[@class=&quot;EnterHsnTsnView__inputGroup--2EueR&quot;]/div[@class=&quot;EnterHsnTsnView__input--20DCF&quot;]/div[@class=&quot;TextField__textFieldContainer--3tI_0&quot;]/div[@class=&quot;TextField__textInputContainer--2DCeU&quot;]/input[@class=&quot;TextInput__textInput--3aA1s EnterHsnTsnView__inputField--28BxH&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='tsn']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='root']/div/div[3]/div/div[2]/div/div/div/form/div[3]/div[3]/div/div/input</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/input</value>
   </webElementXpaths>
</WebElementEntity>
